version: '3.4'

services:
  kitchenbackend:
    image: kitchenbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
